WITH NORTHWIND_TABLES AS
(
	SELECT TABLE_SCHEMA,
	TABLE_NAME
	FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME NOT LIKE '%pg_%'AND TABLE_SCHEMA LIKE 'public'
),
NORTHWIND_COLUMNS_COUNT AS
(
	SELECT TABLE_NAME,
	COUNT(TABLE_NAME) AS NUMBER_OF_COLUMNS
	FROM INFORMATION_SCHEMA.COLUMNS
	GROUP BY TABLE_NAME
)	
SELECT
NORTHWIND_TABLES.TABLE_NAME,
(
	XPATH
 (
	 'row/c/text()',QUERY_TO_XML
  (
	  FORMAT('select count(*) as c from %I.%I',NORTHWIND_TABLES.TABLE_SCHEMA,NORTHWIND_TABLES.TABLE_NAME
			)
	  ,FALSE,TRUE,''
  )
 )
)[1]::text::int AS number_of_rows,
NORTHWIND_COLUMNS_COUNT.NUMBER_OF_COLUMNS
FROM NORTHWIND_TABLES
INNER JOIN NORTHWIND_COLUMNS_COUNT ON NORTHWIND_TABLES.TABLE_NAME = NORTHWIND_COLUMNS_COUNT.TABLE_NAME
ORDER BY "number_of_rows" DESC;
