 WITH
 	CONNECTION_TABLE AS
	(SELECT *,
			UNNEST(CONFKEY) AS FOREIGN_KEY_COLUMN,
			UNNEST(CONKEY) AS PRIMARY_KEY_COLUMN
		FROM PG_CATALOG.PG_CONSTRAINT
		WHERE CONTYPE like 'f'),
	
FOREIGN_KEY_TABLES AS
(SELECT DISTINCT PGC.OID,
		PGC.RELNAME
	FROM PG_CATALOG.PG_CLASS PGC
	INNER JOIN CONNECTION_TABLE CT ON CT.CONFRELID = PGC.OID),
	
PRIMARY_KEY_TABLES AS
(SELECT DISTINCT PGC.OID,
		PGC.RELNAME
	FROM PG_CATALOG.PG_CLASS PGC
	INNER JOIN CONNECTION_TABLE CT ON CT.CONRELID = PGC.OID),
	
TABLE_COLUMNS AS
(SELECT TABLE_NAME,
		COLUMN_NAME,
		ORDINAL_POSITION,
		DATA_TYPE
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME not like '%pg_%' )
	
SELECT CT.CONNAME AS CONNECTION_NAME,
	PGC_P.RELNAME AS PRIMARY_KEY_TABLE,
	TC_P.COLUMN_NAME PRIMARY_KEY_COLUMN,
	PGC_F.RELNAME AS FOREIGN_KEY_TABLE,
	TC_F.COLUMN_NAME FOREIGN_KEY_COLUMN,
	TC_P.DATA_TYPE AS KEY_DATA_TYPE
	
FROM CONNECTION_TABLE CT
INNER JOIN FOREIGN_KEY_TABLES PGC_F ON CT.CONFRELID = PGC_F.OID
INNER JOIN PRIMARY_KEY_TABLES PGC_P ON CT.CONRELID = PGC_P.OID
INNER JOIN TABLE_COLUMNS TC_F ON PGC_F.RELNAME = TC_F.TABLE_NAME
	AND CT.FOREIGN_KEY_COLUMN = TC_F.ORDINAL_POSITION
INNER JOIN TABLE_COLUMNS TC_P ON PGC_P.RELNAME = TC_P.TABLE_NAME
	AND CT.PRIMARY_KEY_COLUMN = TC_P.ORDINAL_POSITION

ORDER BY primary_key_table, foreign_key_table
